export const HANDLE_STAR = 'HANDLE_STAR';
export const LOAD_PAGE_BROWSER = 'LOAD_PAGE_BROWSER';
export const DELETE_FAVORITES = 'DELETE_FAVORITES';
export const IS_SEARCH = 'IS_SEARCH';
export const HANDLE_OPEN_MODAL = 'HANDLE_OPEN_MODAL';
export const LOAD ='LOAD';